name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.16]
    
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
      - name: Install packages
        run: npm install
      - name: Build page
        run: npm run build
      - name: Deploy to gh-pages
        uses: peaceiris/actions-github-pages@v2
        with:
          deploy-key: ${{secrets.ACTIONS_DEPLOY_KEY}}
          publish_dir: ./build
